### ISSUE TITLE
Multiple camera setup

### ISSUE THREAD

**Issue by MjdMahasneh** [jtcass01/DigiCam#2]
I know that DigiCamControl has the option for using multiple cameras, is this also possible using DigiCam library? 

I have looked thoroughly into the documentation available and investigated the source and couldn't find much. Apologies if this is not considered an issue? I am working on a research project and in need to use multiple DSRL sensors.

Looking forward to hearing back from you.

**Comment by jtcass01** [comment]
Sorry for the late reply @MjdMahasneh . This library doesn't support multiple cameras because the driver I am wrapping around didn't support it at the time of implementation.  That being said this code was initially developed 5 years ago.  It may be possible now and if you find anything in the documentation that is relevant please let me know.
